apiVersion: v2
name: wg-easy
description: >-
  Using the offical wg-easy/wg-easy image with almost any environment variables
  for K8s. Supporting Init Mode.
type: application
version: 1.0.0
appVersion: 15.3.0
icon: >-
  https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wg-easy/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wg-easy
    - name: Offical wg-easy Documentation
      url: https://wg-easy.github.io/wg-easy/latest/
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: changed
      description: "wg-easy: serviceAccount.automount now defaults to false."
    - kind: added
      description: "wg-easy: add NetworkPolicy, PDB, commonLabels/Annotations and scheduling controls"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/bc5e3bedcf2cf6ba7430c9916dec7f6ccabe1d81
    - kind: added
      description: "wg-easy: harden pod/container security defaults"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/595ebca124c2e4942fb83c6aa80ca874f9a458a4
  artifacthub.io/containsSecurityUpdates: false
  artifacthub.io/images: |
    - name: wg-easy
      image: ghcr.io/wg-easy/wg-easy:15.3.0
keywords:
  - wireguard
  - vpn
  - wg-easy
