## Prerequisites for externalDB.values.yaml
## kubectl apply -f externalDB.secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-test-secret
type: Opaque
stringData:
  wordpress.username: admin
  wordpress.password: S3cr3tP@ssw0rd
  wordpress.email: admin@example.com
  db.username: dbuser
  db.password: S3cureDBP@ss
