## Prerequisites for multisite-subdomain.values.yaml
## kubectl apply -f multisite-subdomain.secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-multisite-subdomain-secret
type: Opaque
stringData:
  wordpress.username: networkadmin
  wordpress.password: NetworkAdminP@ss123
  wordpress.email: admin@example.com
  mariadb-root-password: RootDBP@ssword123
  mariadb-password: WordPress_DB_P@ss123
