## Sample: SMTP secret
## Create this Secret before installing the chart.
## kubectl create secret generic gmail-smtp-secret --from-literal=password=my-app-password

apiVersion: v1
kind: Secret
metadata:
  name: gmail-smtp-secret
type: Opaque
stringData:
  password: "your-smtp-password-here"
