{
 "title": "WireGuard wg-easy",
 "description": "Dashboard for wg-easy exporter\r\nhttps://github.com/wg-easy/wg-easy",
 "tags": [
  "prometheus",
  "network",
  "Wireguard",
  "wg-easy"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(wireguard_configured_peers,job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(wireguard_configured_peers{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Configured Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_configured_peers{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enabled Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_enabled_peers{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_connected_peers{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "wireguard_latest_handshake_seconds{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (wireguard_received_bytes{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by(name) (wireguard_sent_bytes{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes{job=\"$job\", instance=\"$node\"}[5m])",
     "legendFormat": "received {{name}}"
    },
    {
     "expr": "irate(wireguard_sent_bytes{job=\"$job\", instance=\"$node\"}[5m])",
     "legendFormat": "sent {{name}}"
    }
   ]
  }
 ]
}