{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wireguard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
  {{- $saAnnotations := merge (dict) (.Values.serviceAccount.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  {{- with $saAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
