wordpress:
  init:
    enabled: true
    existingSecret: "wordpress-verify-secret"
    firstname: "John"
    lastname: "Doe"
    title: "verify chart"
    customInitConfigMap:
      name: "wordpress-verify-config"
    jwt:
      enabled: true
    applicationPassword:
      name: "API Access"
      outputSecret:
        name: "wordpress-verify-token-johndoe"
        usernameKey: "WP_USERNAME"
        passwordKey: "WP_APP_PASSWORD"
        urlKey: "WP_SITE_URL"
  language: "de_DE"
  muPluginsConfigMaps:
    - name: wordpress-verify-config
      key: custom-security.php
  plugins:
    - name: "wordpress/mcp-adapter"
      activate: true
      autoupdate: true
    - name: "enable-abilities-for-mcp"
      activate: true
      autoupdate: true
    - name: "redis-cache"
      activate: true
      autoupdate: true
  themes:
    - name: "blocksy"
      activate: false
      autoupdate: true
    - name: "https://creativethemes.com/downloads/blocksy-child.zip"
      slug: "blocksy-child" # Required for URL themes: enables autoupdate, sites[] and skip-if-installed
      activate: true
      autoupdate: true
  users:
    - username: "johnsmith"
      email: "john.smith@example.com"
      displayname: "John Smith"
      firstname: "John"
      lastname: "Smith"
      role: "contributor"
      sendEmail: false
      applicationPassword:
        name: "API Access"
        outputSecret:
          name: "wordpress-verify-token-johnsmith"
          usernameKey: "WP_USERNAME"
          passwordKey: "WP_APP_PASSWORD"
          urlKey: "WP_SITE_URL"
  configExtraSecret:
    name: "wordpress-verify-secret"
  htaccessConfigMap: "wordpress-verify-config"
  url: "http://192.168.178.21:30911"
  smtp:
    enabled: true
    host: smtp.gmail.com
    port: 587
    encryption: tls
    fromName: "Wordpress Verify"
    auth: true
    existingSecret: wordpress-verify-secret
    existingSecretPasswordKey: smtp.password
    existingSecretUsernameKey: smtp.username
    existingSecretFromEmailKey: smtp.fromEmail
controllerType: statefulset
replicaCount: 2
service:
  nodePorts:
    http: 30911
storage:
  accessModes:
    - ReadWriteOnce
  resourcePolicy: "" # Delete PVC on helm uninstall
apache:
  customPhpConfigMap: "wordpress-verify-config"
metrics:
  wordpress:
    enabled: true
    serviceMonitor:
      existingSecret: "wordpress-verify-secret"
    grafanaDashboard:
      enabled: true
      namespace: "monitoring"
  apache:
    enabled: true
mariadb:
  auth:
    database: "wordpress_db"
    username: "wordpress_db_user"
    existingSecret: "wordpress-verify-secret"
valkey:
  enabled: true
  createConfig: true
