apiVersion: v2
name: wireguard
description: >-
  Using the offical linuxserver/wireguard image with almost any environment
  variables for K8S. Supporting server and client mode.
type: application
version: 2.0.0
appVersion: 1.0.20250521-r1-ls116
icon: >-
  https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wireguard/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wireguard
    - name: Offical WireGuard Repository
      url: https://github.com/linuxserver/docker-wireguard
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: changed
      description: "the container no longer runs `privileged: true` by default and `updateStrategy.type` defaults to Recreate. Set `securityContext` explicitly to restore the previous behaviour."
    - kind: added
      description: "run wireguard without privileged by default, add loadKernelModule"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/56bf4721a45094628c9ebbac384ad32135c23d68
    - kind: fixed
      description: "wireguard: update unit tests for non-privileged default"
      links:
        - name: GitHub
          url: https://github.com/SlyBase/helm-charts/commit/52f67a604947bcdb87cb479076ffdfaee9f62e3b
  artifacthub.io/containsSecurityUpdates: false
  artifacthub.io/images: |
    - name: wireguard
      image: docker.io/linuxserver/wireguard:1.0.20250521-r1-ls116
keywords:
  - wireguard
  - vpn
  - linuxserver
