{{- if and (empty .Values.storage.existingClaim) (ne .Values.controllerType "statefulset") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.storage.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $pvcAnnotations := merge (dict) (.Values.storage.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  {{- $rp := .Values.storage.resourcePolicy }}
  {{- if $rp }}{{- $_ := set $pvcAnnotations "helm.sh/resource-policy" $rp }}{{- end }}
  {{- with $pvcAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  {{- if .Values.storage.selector }}
  selector:
    {{- toYaml .Values.storage.selector | nindent 4 }}
  {{- end }}
{{- end }}